tables:
    - name: user
      alias: U
      columns:
          - name: uuid
            field: UUID
          - name: username
            field: Username
          - name: password 
            field: Password
          - name: givenName 
            field: GivenName
          - name: surname 
            field: Surname
