// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import morph "github.com/freerware/morph"

// Loader is an autogenerated mock type for the Loader type
type Loader struct {
	mock.Mock
}

// Load provides a mock function with given fields: path
func (_m *Loader) Load(path string) (morph.Configuration, error) {
	ret := _m.Called(path)

	var r0 morph.Configuration
	if rf, ok := ret.Get(0).(func(string) morph.Configuration); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(morph.Configuration)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
