name: CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.21", "1.22", "1.23", "1.24"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version
      - name: Run Unit Tests
        run: make tests
      - uses: codecov/codecov-action@v4
        name: Upload Code Coverage
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./morph.coverprofile
          fail_ci_if_error: true
          verbose: true
